export const ALLOWED_COLUMNS: Record<string, Record<string, string>> = {
  deal: {
    dealName: "商談名",
    stage: "ステージ",
    amount: "金額",
    probability: "確度",
    expectedCloseDate: "クローズ予定日",
    nextAction: "次回アクション",
    riskLevel: "リスクレベル",
    activityCount: "活動数",
    meetingCount: "商談数",
    callCount: "コール数",
    emailCount: "メール数",
    lastActivityAt: "最終活動日",
    createdAt: "登録日",
    "company.companyName": "顧客企業",
    "contact.fullName": "担当者",
    "owner.name": "商談担当者",
    "salesRep.name": "営業担当",
  },
  company: {
    companyName: "会社名",
    industry: "業種",
    subIndustry: "サブ業種",
    status: "ステータス",
    tier: "ティア",
    employeeSize: "規模",
    annualRevenue: "年商",
    healthScore: "ヘルススコア",
    country: "国",
    city: "市区町村",
    createdAt: "登録日",
  },
  contact: {
    fullName: "氏名",
    email: "メールアドレス",
    phone: "電話番号",
    department: "部署",
    title: "役職",
    "company.companyName": "所属企業",
    createdAt: "登録日",
  },
  activity: {
    type: "種別",
    subject: "件名",
    outcome: "結果",
    durationMinutes: "所要時間(分)",
    activityDate: "活動日",
    nextAction: "次回アクション",
    "owner.name": "実施者",
    "company.companyName": "企業",
    "contact.fullName": "コンタクト",
    "deal.dealName": "商談",
    createdAt: "登録日",
  },
  user: {
    name: "氏名",
    email: "メールアドレス",
    department: "部署",
    title: "役職",
    role: "ロール",
    status: "ステータス",
    "manager.name": "マネージャー",
    createdAt: "登録日",
  },
};
